### ISSUE TITLE
List plugin on the WordPress plugin registry as DocumentCloud

### ISSUE THREAD

**Issue by eyeseast** [documentcloud/wordpress-documentcloud#1]
Here's the old version: http://wordpress.org/plugins/navis-documentcloud/

**Comment by reefdog** [comment]
Do we start a new one, or update that one? If the latter, presumably we do so through the svn repo (blarg)? @eyeseast would you consider giving @knowtheory or I access to it? (I'm the new DocumentCloud dev; also hi!)

**Comment by reefdog** [comment]
Internally done in f6ccc343942f66896bd12d8347e8be7e19260796, still need to figure out how to rename/update WP plugin directory.

**Comment by eyeseast** [comment]
This was a pain to upload the first time, and I haven't tried to do it again. Where I have it in production, I'm pulling straight from Github.

Might be simpler to just upload a new version under the right name. The WordPress plugin registry is still [one giant svn repo](https://developer.wordpress.org/plugins/wordpress-org/#restrictions) (ick) so that's another complication.

**Comment by reefdog** [comment]
[Boom!](https://wordpress.org/plugins/documentcloud/)

Whenever we tag a new version here, I'll manually update the new SVN repo. @eyeseast Do you want access to the new plugin repo? Happy to provide it unless you think you'll never want to mess with the WP directory side of things.

And what do you want to do with Navis DocumentCloud? Keep alive for history, ask WP to remove from directory, point to the new one…?

**Comment by eyeseast** [comment]
I don't think I need access to the SVN repo, unless you need a bus-factor backup plan.

If WP can remove and redirect the old link, I think that's ideal. Not exactly sure how to do that. 

We should also have Largo (ping @aschweigert) point to this version instead of the other one.

**Comment by reefdog** [comment]
I'll contact WP support to see what the options are for redirecting. Presumably they'll need to contact you.

I added you as a repo committer just in case, yes, the bus. @knowtheory let me know if you want to sign up for a WP account and have me add you too. Just in case that bus bounces off me and hits Chris.

**Comment by knowtheory** [comment]
I already have a wp account (unsurprisingly as knowtheory) :) and yep would be great to be on the repo too plz!
