### ISSUE TITLE
Add responsive options to shortcode

### ISSUE THREAD

**Issue by eyeseast** [documentcloud/wordpress-documentcloud#14]
Now that @documentcloud is moving towards a responsive viewer (https://github.com/documentcloud/document-viewer/pull/46) we should add the options to the shortcode. Question is, should embeds be responsive by default?

**Comment by reefdog** [comment]
+1 to the option being added, but it's not ready yet to be the default.

**Comment by reefdog** [comment]
Offline consensus is that we can indeed default to responsive. Making it so.

**Comment by eyeseast** [comment]
Seems reasonable to me, too.

On Tue, Apr 28, 2015 at 2:48 PM, Justin Reese <notifications@github.com>
wrote:

> Offline consensus is that we can indeed default to responsive. Making it
> so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/documentcloud/wordpress-documentcloud/issues/14#issuecomment-97167920>
> .
>



-- 
Chris Amico
Glass Eye Media LLC <http://glasseyemedia.org>

**Comment by reefdog** [comment]
I just realized this means `width/maxwidth` effectively have no impact unless you set `responsive:false`. Guess we should document that.
