### ISSUE TITLE
Inserting shortcode with widget triggers "tinyMCE.getInstanceById is not a function" error

### ISSUE THREAD

**Issue by reefdog** [documentcloud/wordpress-documentcloud#23]
1. Install and activate the plugin (natch)
2. Go to a post
3. Flip to Visual mode
4. Click the DocumentCloud toolbar icon
5. Add a URL and whatever
6. Click "Insert"

What should happen: The shortcode composes and inserts into the content.

What happens: Widget seems to reload, console shows error: "Uncaught TypeError: tinyMCE.getInstanceById is not a function"

Unsure when this behavior started, but a clean installation of WP 3.9.1 and the plugin at 1b84674c6dd0a46d4db8d6879982eca5436aef9b still threw the error.

**Comment by aschweigert** [comment]
Probably when they updated to the new version of TinyMCE (3.8 or 3.9?), we had a similar issue with some other buttons from original Argo stuff to insert modules into the body of posts. I'll see if I can hunt down what the fix for that was...

**Comment by eyeseast** [comment]
That Argo stuff is really getting to be a long time ago.

**Comment by aschweigert** [comment]
Looks like we just moved that fix to another site and this is the relevant bit here: https://bitbucket.org/projectlargo/theme-lensnola/commits/2c8f0ca0669c/#Ljs/tinymce/plugins/largo/tinymce.jsT5

**Comment by knowtheory** [comment]
oh man, thanks for digging that up!  (also, the lens is hosted up on bitbucket?)

**Comment by aschweigert** [comment]
we keep some of our child themes on bitbucket, but also their site is actually in a sandboxed WP instance because the code quality from the developers they worked with is...questionable.

**Comment by reefdog** [comment]
TinyMCE stuff yanked entirely. Will eventually try to add something similar back in, but tracking in #25.
