### ISSUE TITLE
Decommission old Navis-DocumentCloud plugin

### ISSUE THREAD

**Issue by anthonydb** [documentcloud/wordpress-documentcloud#24]
The old one is going to rank high in Google search for a while -- we should see about getting it deleted or pointed to the new one. This was mentioned in another issue that's now closed so getting it on the radar.

**Comment by reefdog** [comment]
Emailed this to plugins@wordpress.com yesterday:

> Hi there-
> 
> Several years ago, Chris Amico (@chrisamico, CC’ed on this email) wrote a plugin to allow embedding DocumentCloud resources in WP content using shortcodes. He released it as Navis DocumentCloud (https://wordpress.org/plugins/navis-documentcloud/). Subsequently, DocumentCloud itself forked the project in GitHub and, with Chris’s guidance and participation, became the maintainers of the project.
> 
> We recently renamed it just “DocumentCloud” to reflect its new first-party status, made several significant updates, and released it as a new plugin: https://wordpress.org/plugins/documentcloud/
> 
> We’d like to remove the Navis DocumentCloud plugin and redirect that URL to the new plugin. Chris has approved this approach: https://github.com/documentcloud/wordpress-documentcloud/issues/1#issuecomment-97972543 (Chris, feel free to chime in if I’m misstating anything!)
> 
> Is that possible? Failing that, what’s the suggested approach for replacing one plugin with another (given that we wanted the URL to change too)?
> 
> Thanks,
> 
> – Justin Reese
> Developer at DocumentCloud
> 
> PS: My WP account (@reefdog) uses my personal email, which I’m sending this request from, but you can also reach me at justin@documentcloud.org.

**Comment by reefdog** [comment]
Received this from WordPress:

> Guess what we can't do?
> 
> Rename a plugin.
> 
> Plugin URLs cannot be changed. The slug is a unique item in our system that uniquely identifies the plugin. It is in the URL, it is the directory name that your plugin uses on people's sites, and it is part of the matching name for the plugins update process in the WordPress core code.
> 
> Once the URL is created, it cannot be altered in any way.
> 
> Are you sure you want to rename the slug, though and not just give it a different display name? Those are different things. The slug (i.e. the part that makes the WP URL wordpress.org/plugins/YOURPLUGIN and the wp-content/plugins/YOURPLUGIN ) cannot be changed at all. But the displayed name can be whatever you want to make it via your readme.
> 
> If you really want to change the name, the only thing we can do is close that plugin and you can submit a new one. But keep in mind, you'll lose any followers using your old plugin, and they will never get update notifications to use or switch to the new one. If this is a new plugin, that's usually okay. If it's an old one, though, this is a very bad idea for something so minor. You'll lose users, forever.

No new information, but sounds like they can't/won't offer an actual redirect from /navis-documentcloud/ to /documentcloud/. I'm getting nervous about just sending the former to /dev/null, so suggested to @eyeseast that we hose all the plugin files and replace the `readme.txt` with instructions for finding the new plugin. WP may eventually frown upon that, but with the alternative being deletion, I don't much mind.

**Comment by knowtheory** [comment]
:+1: you'd think they'd appreciate that slugs are important, but then again writing something that tracks what supersedes what inside of wordpress would be a bummer.

**Comment by reefdog** [comment]
Working with Tom Downing at WITF on this. Suggested plan of attack:

- Update `readme.txt` to point to DC
- Add admin notice directing installed users to uninstall Navis DC and install DC

**Comment by reefdog** [comment]
Okay, @tomdowning has okayed this approach and @eyeseast has given me commit access to https://github.com/argoproject/navis-documentcloud. I'm making the edits.

Last step will be actually deploying this to the [WordPress plugin directory](https://wordpress.org/plugins/navis-documentcloud/). Still working on getting that authorization.

**Comment by knowtheory** [comment]
This is done!  Congratulations to everyone!  We're first party now!  A lot of fun stuff we can and should do! :)

And @aschweigert, @eyeseast & @tomdowning, lets sit down (virtually) and figure out some strategic directions sometime soon.

@reefdog and i are basically resolved that we'd like to use the Wordpress plugin as our primary target for CMS integration, testing and prototyping, because we have full control over the integration and testing process.  From our end i think we'll continue to create tickets for discussion prior to executing along any particular course of action.

We would love to have partners and input :)

**Comment by aschweigert** [comment]
sweet, definitely let us know if there's anything we can do to help (I know you will, but just reiterating)
