### ISSUE TITLE
Add to WordPress VIP shared plugins repository

### ISSUE THREAD

**Issue by bcampeau** [documentcloud/wordpress-documentcloud#30]
One of our clients is interested in using your plugin on WordPress VIP. I see some minor code formatting and minor issues to resolve so it would pass their code review process. Would you be open to a pull request for this before we invest the effort? We can also help get this into the review queue for WordPress VIP since we're a partner.

Your plugin would then also be available to all WordPress VIP sites, which include some of the largest publishers in the world: https://vip.wordpress.com/plugins/

Let me know your thoughts on this. Thanks.

**Comment by knowtheory** [comment]
:100:% interested and happy to work with you on this. cc/ @reefdog 

Our intent has been to treat our wordpress plugin as a primary target for future feature development w/r/t our externally facing APIs.  So, at the very least we'd love to chat more about the ongoing expectations set by the VIP review process with someone who has experience with it!

**Comment by bcampeau** [comment]
There is no real expectation other than to continue to support the plugin as needed, which is as often or little as you like. Every line of code on VIP is shared with all of WordPress.com, so there is a pretty stringent code review process for new plugins. 

We've been through it many times, so I figured it would be easier to start with a pull request of my suggestions. We can help get it into their repository since you're not currently a partner. Expect to see something in the next week or so and we can go from there.

**Comment by reefdog** [comment]
:+1: Thanks @bcampeau!

**Comment by bcampeau** [comment]
Just wanted to let you know this has finally been sent your way in https://github.com/documentcloud/wordpress-documentcloud/pull/32.

Thanks.

**Comment by reefdog** [comment]
This is terrific, @bcampeau, thanks! I'll take a look at it this week. We really appreciate your work on this.

**Comment by reefdog** [comment]
@bcampeau When you reach out to the VIP folks, have them contact us at support@documentcloud.org if they want to get a DocumentCloud account for testing this. Although they can also experiment with generating shortcodes and embedding raw URLs for any public document, like https://www.documentcloud.org/documents/282753-lefler-thesis.html

**Comment by reefdog** [comment]
:arrow_up: That's obviously meant for after I actually tag and release your edits, hah. Should be this week, just want to fix a couple bugs I found.

**Comment by reefdog** [comment]
One question, @bcampeau: I noticed you converted soft tabs (spaces) to tabs. That doesn't seem to be a WP VIP requirement. Is that just a stylistic preference, or is there a VIP reason to keep them tabs?

**Comment by bcampeau** [comment]
It's WordPress coding standards, not VIP. However, they do make the code more readable and is their preferred format as well.

**Comment by reefdog** [comment]
Got it. We'll conform, then. Thanks!

**Comment by reefdog** [comment]
Tagged and deployed.

**Comment by bcampeau** [comment]
Great, thanks.

On Thu, Feb 25, 2016 at 6:35 PM, Justin Reese <notifications@github.com>
wrote:

> Tagged and deployed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/documentcloud/wordpress-documentcloud/issues/30#issuecomment-189035226>
> .
>



-- 
Brad Campeau-Laurion
Partner, Alley Interactive
212-257-2154

**Comment by bcampeau** [comment]
@reefdog VIP asked for a couple minor changes, which I've handled in #41 if you can review and merge. 

Thanks.

**Comment by reefdog** [comment]
Merged in, thanks @bcampeau. Presumably I need to actually release a new version to get the VIP team to re-evaluate? Bit of a bummer, since it'll prompt people to upgrade, but seems worthwhile.

**Comment by bcampeau** [comment]
I'll just notify them the changes have been merged and they'll just pull the latest from the master branch.

**Comment by reefdog** [comment]
Oh, excellent, thanks @bcampeau!

**Comment by bcampeau** [comment]
There's been a bit of a swerve here at the last minute. VIP is not accepting any new plugins to the shared plugins repository. Going forward, they're going to keep an approved plugins list and the latest version that has been reviewed. Clients that wish to use these plugins can commit them directly to their own repository.

Therefore, you can advise anyone on VIP that wishes to use this plugin they may include it and it will not incur any additional code review. They should be formalizing and publicizing this list and the new procedure in the coming weeks.

**Comment by reefdog** [comment]
So it's moving from an enforced whitelist to a "verified" badge, basically?

Thanks for spearheading this regardless, @bcampeau. The plugin is better for it.

**Comment by bcampeau** [comment]
I'm not really sure how this will work logistically, but something like that.

**Comment by knowtheory** [comment]
@bcampeau btw, with your end goal of getting your client up and running with our plugin... is there anything we can do to help you on that front, or are you effectively stymied until WP.com comes out with their new process?

**Comment by bcampeau** [comment]
No holdup. The plugin is live on their site via the method I described - including it in the theme.
