### ISSUE TITLE
Rename main class

### ISSUE THREAD

**Issue by eyeseast** [documentcloud/wordpress-documentcloud#7]
`class Navis_DocumentCloud` should become `class WP_DocumentCloud` or just `class DocumentCloud`.

Any reason not to do this?

**Comment by reefdog** [comment]
No reason I can think of… unless anyone out there was extending it. Seems unlikely.

**Comment by reefdog** [comment]
Done in 41d12de41cfd90063916cf3d8654e5ae0f9a4585
